package com.tre.sololeveling.config;

import net.minecraftforge.common.ForgeConfigSpec;

public final class ModConfigs {
    public static final ForgeConfigSpec SERVER_SPEC;
    public static final ForgeConfigSpec CLIENT_SPEC;
    public static final ForgeConfigSpec.DoubleValue XP_MULTIPLIER;
    public static final ForgeConfigSpec.IntValue MAX_HUNTER_LEVEL;
    public static final ForgeConfigSpec.BooleanValue PRESERVE_ON_DEATH;
    public static final ForgeConfigSpec.DoubleValue XP_CURVE_BASE;
    public static final ForgeConfigSpec.DoubleValue XP_CURVE_EXPONENT;
    public static final ForgeConfigSpec.DoubleValue XP_CURVE_LINEAR;
    public static final ForgeConfigSpec.IntValue STAT_POINTS_PER_LEVEL;
    public static final ForgeConfigSpec.IntValue AUTOMATIC_STAT_GAIN_PER_LEVEL;
    public static final ForgeConfigSpec.IntValue MAX_PRIMARY_STAT;
    public static final ForgeConfigSpec.DoubleValue STRENGTH_DAMAGE_PER_POINT;
    public static final ForgeConfigSpec.DoubleValue AGILITY_SPEED_PER_POINT;
    public static final ForgeConfigSpec.DoubleValue AGILITY_SPEED_CAP;
    public static final ForgeConfigSpec.DoubleValue STAMINA_HEALTH_PER_POINT;
    public static final ForgeConfigSpec.DoubleValue STAMINA_HEALTH_CAP;
    public static final ForgeConfigSpec.IntValue BASE_MANA;
    public static final ForgeConfigSpec.IntValue MANA_PER_LEVEL;
    public static final ForgeConfigSpec.IntValue MANA_PER_INTELLIGENCE;
    public static final ForgeConfigSpec.DoubleValue HEALTH_REGEN_BASE;
    public static final ForgeConfigSpec.DoubleValue HEALTH_REGEN_PER_STAMINA;
    public static final ForgeConfigSpec.DoubleValue HEALTH_REGEN_CAP;
    public static final ForgeConfigSpec.IntValue HEALTH_REGEN_COMBAT_DELAY_SECONDS;
    public static final ForgeConfigSpec.DoubleValue MANA_REGEN_BASE;
    public static final ForgeConfigSpec.DoubleValue MANA_REGEN_PER_INTELLIGENCE;
    public static final ForgeConfigSpec.DoubleValue CRITICAL_BASE_CHANCE;
    public static final ForgeConfigSpec.DoubleValue CRITICAL_CHANCE_PER_SENSE;
    public static final ForgeConfigSpec.DoubleValue CRITICAL_CHANCE_PER_AGILITY;
    public static final ForgeConfigSpec.DoubleValue CRITICAL_CHANCE_CAP;
    public static final ForgeConfigSpec.DoubleValue CRITICAL_DAMAGE_BASE;
    public static final ForgeConfigSpec.DoubleValue CRITICAL_DAMAGE_PER_STRENGTH;
    public static final ForgeConfigSpec.DoubleValue CRITICAL_DAMAGE_PER_SENSE;
    public static final ForgeConfigSpec.DoubleValue CRITICAL_DAMAGE_CAP;
    public static final ForgeConfigSpec.DoubleValue EVASION_PER_AGILITY;
    public static final ForgeConfigSpec.DoubleValue EVASION_PER_SENSE;
    public static final ForgeConfigSpec.DoubleValue EVASION_CAP;
    public static final ForgeConfigSpec.IntValue ACTIVE_SHADOW_MAX;
    public static final ForgeConfigSpec.BooleanValue PVP_ABILITIES;
    public static final ForgeConfigSpec.BooleanValue HUD_ENABLED;
    public static final ForgeConfigSpec.DoubleValue HUD_SCALE;
    public static final ForgeConfigSpec.DoubleValue PARTICLE_DENSITY;
    public static final ForgeConfigSpec.BooleanValue CAMERA_SHAKE;

    static {
        ForgeConfigSpec.Builder server = new ForgeConfigSpec.Builder();
        server.push("progression");
        XP_MULTIPLIER = server.comment("Multiplier applied to hunter XP rewards.").defineInRange("xpMultiplier", 1.0D, 0.0D, 100.0D);
        MAX_HUNTER_LEVEL = server.defineInRange("maximumHunterLevel", 100, 1, 10000);
        PRESERVE_ON_DEATH = server.define("preserveProgressionOnDeath", true);
        XP_CURVE_BASE = server.defineInRange("xpCurveBase", 100.0D, 1.0D, 1_000_000.0D);
        XP_CURVE_EXPONENT = server.defineInRange("xpCurveExponent", 1.55D, 0.1D, 5.0D);
        XP_CURVE_LINEAR = server.defineInRange("xpCurveLinear", 0.0D, 0.0D, 1_000_000.0D);
        STAT_POINTS_PER_LEVEL = server.defineInRange("statPointsPerLevel", 5, 0, 1000);
        AUTOMATIC_STAT_GAIN_PER_LEVEL = server.defineInRange("automaticStatGainPerLevel", 1, 0, 1000);
        MAX_PRIMARY_STAT = server.defineInRange("maximumPrimaryStat", 10000, 1, 1_000_000);
        server.pop().push("attributes");
        STRENGTH_DAMAGE_PER_POINT = server.defineInRange("strengthDamagePerPoint", 0.15D, 0.0D, 100.0D);
        AGILITY_SPEED_PER_POINT = server.defineInRange("agilitySpeedPerPoint", 0.0015D, 0.0D, 1.0D);
        AGILITY_SPEED_CAP = server.defineInRange("agilitySpeedBonusCap", 0.20D, 0.0D, 5.0D);
        STAMINA_HEALTH_PER_POINT = server.defineInRange("staminaHealthPerPoint", 0.40D, 0.0D, 100.0D);
        STAMINA_HEALTH_CAP = server.defineInRange("staminaHealthBonusCap", 80.0D, 0.0D, 10000.0D);
        BASE_MANA = server.defineInRange("baseMana", 100, 1, 1_000_000);
        MANA_PER_LEVEL = server.defineInRange("manaPerLevel", 2, 0, 10000);
        MANA_PER_INTELLIGENCE = server.defineInRange("manaPerIntelligence", 8, 0, 10000);
        HEALTH_REGEN_BASE = server.defineInRange("healthRegenPerSecondBase", 0.10D, 0.0D, 100.0D);
        HEALTH_REGEN_PER_STAMINA = server.defineInRange("healthRegenPerStamina", 0.015D, 0.0D, 10.0D);
        HEALTH_REGEN_CAP = server.defineInRange("healthRegenPerSecondCap", 5.0D, 0.0D, 1000.0D);
        HEALTH_REGEN_COMBAT_DELAY_SECONDS = server.defineInRange("healthRegenCombatDelaySeconds", 5, 0, 600);
        MANA_REGEN_BASE = server.defineInRange("manaRegenPerSecondBase", 2.0D, 0.0D, 10000.0D);
        MANA_REGEN_PER_INTELLIGENCE = server.defineInRange("manaRegenPerIntelligence", 0.05D, 0.0D, 100.0D);
        server.pop().push("combat");
        CRITICAL_BASE_CHANCE = server.defineInRange("criticalBaseChance", 0.02D, 0.0D, 1.0D);
        CRITICAL_CHANCE_PER_SENSE = server.defineInRange("criticalChancePerSense", 0.0012D, 0.0D, 1.0D);
        CRITICAL_CHANCE_PER_AGILITY = server.defineInRange("criticalChancePerAgility", 0.0002D, 0.0D, 1.0D);
        CRITICAL_CHANCE_CAP = server.defineInRange("criticalChanceCap", 0.60D, 0.0D, 1.0D);
        CRITICAL_DAMAGE_BASE = server.defineInRange("criticalDamageBaseMultiplier", 1.50D, 1.0D, 100.0D);
        CRITICAL_DAMAGE_PER_STRENGTH = server.defineInRange("criticalDamagePerStrength", 0.002D, 0.0D, 10.0D);
        CRITICAL_DAMAGE_PER_SENSE = server.defineInRange("criticalDamagePerSense", 0.005D, 0.0D, 10.0D);
        CRITICAL_DAMAGE_CAP = server.defineInRange("criticalDamageMultiplierCap", 3.0D, 1.0D, 100.0D);
        EVASION_PER_AGILITY = server.defineInRange("evasionChancePerAgility", 0.0010D, 0.0D, 1.0D);
        EVASION_PER_SENSE = server.defineInRange("evasionChancePerSense", 0.0002D, 0.0D, 1.0D);
        EVASION_CAP = server.defineInRange("evasionChanceCap", 0.35D, 0.0D, 1.0D);
        PVP_ABILITIES = server.define("pvpAbilityEffects", false);
        ACTIVE_SHADOW_MAX = server.defineInRange("activeShadowMaximum", 12, 0, 50);
        server.pop();
        SERVER_SPEC = server.build();

        ForgeConfigSpec.Builder client = new ForgeConfigSpec.Builder();
        client.push("interface");
        HUD_ENABLED = client.define("hudEnabled", true);
        HUD_SCALE = client.defineInRange("hudScale", 1.0D, 0.5D, 2.0D);
        PARTICLE_DENSITY = client.defineInRange("particleDensity", 1.0D, 0.0D, 1.0D);
        CAMERA_SHAKE = client.define("cameraShake", true);
        client.pop();
        CLIENT_SPEC = client.build();
    }
    private ModConfigs() {}
}
