package com.tre.sololeveling.quest;

public enum QuestObjectiveType {
    KILL,
    COLLECTION,
    ABILITY_USE,
    MANA_SPENT,
    STAT_ALLOCATION,
    DUNGEON_CLEAR,
    SHADOW_SUMMON,
    SKILL_UNLOCK,
    SYSTEM_OPEN,
    EXERCISE,
    DISTANCE,
    ENEMY_ROLE,
    ENCOUNTER_CONSTRAINT,
    SECRET_DISCOVERY,
    SHADOW_DEVELOPMENT,
    EQUIPMENT_UPGRADE,
    COMBAT_STYLE
}
